"""init

Revision ID: 80d5bf6e8a80
Revises: 
Create Date: 2023-11-06 18:14:04.364640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d5bf6e8a80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awesome_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('control_sum', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awesome_data_control_sum'), 'awesome_data', ['control_sum'], unique=True)
    op.create_index(op.f('ix_awesome_data_data'), 'awesome_data', ['data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_awesome_data_data'), table_name='awesome_data')
    op.drop_index(op.f('ix_awesome_data_control_sum'), table_name='awesome_data')
    op.drop_table('awesome_data')
    # ### end Alembic commands ###
